{% set name = "scikit-bio" %}
{% set version = "0.5.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6343ca0c621e2fcc5d1c042c8be3200664c5325956a83bea751cf1bcc75d1da9

build:
  skip: true  # [win]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy
  run:
    - python
    - lockfile >=0.10.2
    - cachecontrol >=0.11.5
    - decorator >=3.4.2
    - ipython >=3.2.0
    - matplotlib-base >=1.4.3
    - natsort >=4.0.3
    - {{ pin_compatible('numpy') }}
    - pandas >=1.0.0
    - scipy >=1.3.0, <1.9 # https://github.com/biocore/scikit-bio/issues/1818
    - hdmedians >=0.13
    - scikit-learn >=0.19.1
    - pytest
    - h5py

test:
  imports:
    - skbio
    - skbio.alignment
    - skbio.alignment._lib
    - skbio.alignment.tests
    - skbio.diversity
    - skbio.diversity.alpha
    - skbio.diversity.alpha.tests
    - skbio.diversity.beta
    - skbio.diversity.beta.tests
    - skbio.diversity.tests
    - skbio.io
    - skbio.io.format
    - skbio.io.format.tests
    - skbio.io.tests
    - skbio.sequence
    - skbio.sequence.tests
    - skbio.stats
    - skbio.stats.distance
    - skbio.stats.distance.tests
    - skbio.stats.evolve
    - skbio.stats.evolve.tests
    - skbio.stats.ordination
    - skbio.stats.ordination.tests
    - skbio.stats.tests
    - skbio.tests
    - skbio.tree
    - skbio.tree.tests
    - skbio.util
    - skbio.util.tests
  commands:
    - MPLBACKEND='Agg' python -m skbio.test

about:
  home: http://scikit-bio.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.txt
  summary: 'Data structures, algorithms and educational resources for bioinformatics.'
  doc_url: http://scikit-bio.org
  dev_url: https://github.com/biocore/scikit-bio

extra:
  recipe-maintainers:
    - ebolyen
    - wasade
    - mortonjt
    - thermokarst
    - ElDeveloper
