{% set name = "scikit-bio" %}
{% set version = "0.5.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7ae044dc8bee231900248adc3a8659077e76140d56ac9f42bd01fb7981014910

build:
  skip: true  # [win]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - cython
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - lockfile >=0.10.2
    - cachecontrol >=0.11.5
    - decorator >=3.4.2
    - ipython >=3.2.0
    - matplotlib-base >=1.4.3
    - natsort >=4.0.3
    - {{ pin_compatible('numpy') }}
    - pandas >=1.5.0
    - scipy >=1.9.0
    - h5py >=3.6.0
    - hdmedians >=0.14.1
    - pytest

test:
  imports:
    - skbio
    - skbio.alignment
    - skbio.alignment._lib
    - skbio.alignment.tests
    - skbio.diversity
    - skbio.diversity.alpha
    - skbio.diversity.alpha.tests
    - skbio.diversity.beta
    - skbio.diversity.beta.tests
    - skbio.diversity.tests
    - skbio.io
    - skbio.io.format
    - skbio.io.format.tests
    - skbio.io.tests
    - skbio.sequence
    - skbio.sequence.tests
    - skbio.stats
    - skbio.stats.distance
    - skbio.stats.distance.tests
    - skbio.stats.evolve
    - skbio.stats.evolve.tests
    - skbio.stats.ordination
    - skbio.stats.ordination.tests
    - skbio.stats.tests
    - skbio.tests
    - skbio.tree
    - skbio.tree.tests
    - skbio.util
    - skbio.util.tests
  commands:
    - MPLBACKEND='Agg' python -m skbio.test

about:
  home: http://scikit-bio.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Data structures, algorithms and educational resources for bioinformatics.
  doc_url: http://scikit-bio.org
  dev_url: https://github.com/biocore/scikit-bio

extra:
  recipe-maintainers:
    - ebolyen
    - wasade
    - mortonjt
    - thermokarst
    - ElDeveloper
