{% set name = "scikit-bio" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2f62d90fb44990d90593f2312398989c816081868c4cc6aedba170893f397b8c

build:
  skip: true  # [win]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cython
  host:
    - python
    - pip
    - numpy
    - cython
  run:
    - python
    - requests >=2.20.0
    - natsort >=4.0.3
    - {{ pin_compatible('numpy') }}
    - pandas >=1.5.0
    - scipy >=1.9.0
    - h5py >=3.6.0
    - hdmedians >=0.14.1
    - pytest
    - biom-format
    - setuptools

test:
  imports:
    - skbio
    - skbio.alignment
    - skbio.alignment._lib
    - skbio.alignment.tests
    - skbio.diversity
    - skbio.diversity.alpha
    - skbio.diversity.alpha.tests
    - skbio.diversity.beta
    - skbio.diversity.beta.tests
    - skbio.diversity.tests
    - skbio.io
    - skbio.io.format
    - skbio.io.format.tests
    - skbio.io.tests
    - skbio.sequence
    - skbio.sequence.tests
    - skbio.stats
    - skbio.stats.distance
    - skbio.stats.distance.tests
    - skbio.stats.evolve
    - skbio.stats.evolve.tests
    - skbio.stats.ordination
    - skbio.stats.ordination.tests
    - skbio.stats.tests
    - skbio.tests
    - skbio.tree
    - skbio.tree.tests
    - skbio.util
    - skbio.util.tests
  commands:
    - MPLBACKEND='Agg' python -m skbio.test

about:
  home: https://scikit.bio
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Data structures, algorithms and educational resources for bioinformatics.
  doc_url: https://scikit.bio
  dev_url: https://github.com/scikit-bio/scikit-bio

extra:
  recipe-maintainers:
    - qiyunzhu
    - mortonjt
    - wasade
