{% set name = "scikit-bio" %}
{% set version = "0.5.2" %}
{% set sha256 = "566c83249d2d338104d106c3a8ba36fa1afeabf10ead8e95b84605b71c65b743" %}
{% set build_num = "1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [win or py2k]
  number: {{ build_num }}
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy >=1.9.2,<1.14.0
    - nose >=1.3.7
  run:
    - python
    - lockfile >=0.10.2
    - cachecontrol >=0.11.5
    - decorator >=3.4.2
    - ipython >=3.2.0
    - matplotlib >=1.4.3
    - natsort >=4.0.3
    - {{ pin_compatible('numpy') }}
    - pandas >=0.19.2
    - scipy >=0.15.1
    - nose >=1.3.7
    - scikit-learn >=0.19.1
    - xvfbwrapper

test:
  imports:
    - skbio
    - skbio.alignment
    - skbio.alignment._lib
    - skbio.alignment.tests
    - skbio.diversity
    - skbio.diversity.alpha
    - skbio.diversity.alpha.tests
    - skbio.diversity.beta
    - skbio.diversity.beta.tests
    - skbio.diversity.tests
    - skbio.io
    - skbio.io.format
    - skbio.io.format.tests
    - skbio.io.tests
    - skbio.sequence
    - skbio.sequence.tests
    - skbio.stats
    - skbio.stats.distance
    - skbio.stats.distance.tests
    - skbio.stats.evolve
    - skbio.stats.evolve.tests
    - skbio.stats.ordination
    - skbio.stats.ordination.tests
    - skbio.stats.tests
    - skbio.tests
    - skbio.tree
    - skbio.tree.tests
    - skbio.util
    - skbio.util.tests
  commands:
    - python -m skbio.test  # [not linux]
    - MPLBACKEND='Agg' python -m skbio.test  # [linux]

about:
  home: http://scikit-bio.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.txt
  summary: 'Data structures, algorithms and educational resources for bioinformatics.'
  doc_url: http://scikit-bio.org
  dev_url: http://github.com/biocore/scikit-bio

extra:
  recipe-maintainers:
    - ebolyen
    - wasade
    - mortonjt
    - johanneskoester
