{% set name = "scikit-bio" %}
{% set version = "0.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9fa813be66e88a994f7b7a68b8ba2216e205c525caa8585386ebdeebed6428df
  patches:
    - 0001-Build-fixes-for-pandas-0.25.0-and-scipy-1.3.0.patch

build:
  skip: true  # [win or py2k]
  number: 1001
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy
  run:
    - python
    - lockfile >=0.10.2
    - cachecontrol >=0.11.5
    - decorator >=3.4.2
    - ipython >=3.2.0
    - matplotlib >=1.4.3
    - natsort >=4.0.3
    - {{ pin_compatible('numpy') }}
    - pandas >=0.19.2
    - scipy >=0.15.1
    - pytest
    - scikit-learn >=0.19.1
    - hdmedians >=0.13

test:
  imports:
    - skbio
    - skbio.alignment
    - skbio.alignment._lib
    - skbio.alignment.tests
    - skbio.diversity
    - skbio.diversity.alpha
    - skbio.diversity.alpha.tests
    - skbio.diversity.beta
    - skbio.diversity.beta.tests
    - skbio.diversity.tests
    - skbio.io
    - skbio.io.format
    - skbio.io.format.tests
    - skbio.io.tests
    - skbio.sequence
    - skbio.sequence.tests
    - skbio.stats
    - skbio.stats.distance
    - skbio.stats.distance.tests
    - skbio.stats.evolve
    - skbio.stats.evolve.tests
    - skbio.stats.ordination
    - skbio.stats.ordination.tests
    - skbio.stats.tests
    - skbio.tests
    - skbio.tree
    - skbio.tree.tests
    - skbio.util
    - skbio.util.tests
  commands:
    - MPLBACKEND='Agg' python -m skbio.test

about:
  home: http://scikit-bio.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.txt
  summary: 'Data structures, algorithms and educational resources for bioinformatics.'
  doc_url: http://scikit-bio.org
  dev_url: http://github.com/biocore/scikit-bio

extra:
  recipe-maintainers:
    - ebolyen
    - wasade
    - mortonjt
